[2024-04-15T09:05:59.880+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data.extract_data_from_text scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-04-15T09:05:59.917+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data.extract_data_from_text scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-04-15T09:05:59.918+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-04-15T09:05:59.953+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract_data_from_text> on 2024-04-01 00:00:00+00:00
[2024-04-15T09:05:59.976+0000] {standard_task_runner.py:60} INFO - Started process 165 to run task
[2024-04-15T09:05:59.978+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_data', 'extract_data_from_text', 'scheduled__2024-04-01T00:00:00+00:00', '--job-id', '1345', '--raw', '--subdir', 'DAGS_FOLDER/etl_data.py', '--cfg-path', '/tmp/tmpvkqjyz6s']
[2024-04-15T09:05:59.983+0000] {standard_task_runner.py:88} INFO - Job 1345: Subtask extract_data_from_text
[2024-04-15T09:06:00.154+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_data.extract_data_from_text scheduled__2024-04-01T00:00:00+00:00 [running]> on host 41da1b14e620
[2024-04-15T09:06:00.331+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data' AIRFLOW_CTX_TASK_ID='extract_data_from_text' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T00:00:00+00:00'
[2024-04-15T09:06:00.337+0000] {python.py:202} INFO - Done. Returned value was: file does not exist
[2024-04-15T09:06:00.410+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_data, task_id=extract_data_from_text, execution_date=20240401T000000, start_date=20240415T090559, end_date=20240415T090600
[2024-04-15T09:06:01.019+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-15T09:06:01.175+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
