[2024-04-16T18:05:28.337+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: files_ext.exst manual__2024-04-16T18:05:26.410800+00:00 [queued]>
[2024-04-16T18:05:28.343+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: files_ext.exst manual__2024-04-16T18:05:26.410800+00:00 [queued]>
[2024-04-16T18:05:28.343+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-04-16T18:05:28.353+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): exst> on 2024-04-16 18:05:26.410800+00:00
[2024-04-16T18:05:28.359+0000] {standard_task_runner.py:60} INFO - Started process 1367 to run task
[2024-04-16T18:05:28.361+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'files_ext', 'exst', 'manual__2024-04-16T18:05:26.410800+00:00', '--job-id', '2012', '--raw', '--subdir', 'DAGS_FOLDER/files_extraction.py', '--cfg-path', '/tmp/tmp8ckym6nm']
[2024-04-16T18:05:28.362+0000] {standard_task_runner.py:88} INFO - Job 2012: Subtask exst
[2024-04-16T18:05:28.392+0000] {task_command.py:423} INFO - Running <TaskInstance: files_ext.exst manual__2024-04-16T18:05:26.410800+00:00 [running]> on host fdd3cfdf3f53
[2024-04-16T18:05:28.464+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='files_ext' AIRFLOW_CTX_TASK_ID='exst' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T18:05:26.410800+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-16T18:05:26.410800+00:00'
[2024-04-16T18:05:28.566+0000] {logging_mixin.py:188} INFO - Error downloading file: Unable to locate credentials
[2024-04-16T18:05:28.566+0000] {python.py:202} INFO - Done. Returned value was: dags/
[2024-04-16T18:05:28.592+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=files_ext, task_id=exst, execution_date=20240416T180526, start_date=20240416T180528, end_date=20240416T180528
[2024-04-16T18:05:28.613+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-16T18:05:28.627+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
