[2024-04-15T12:30:14.175+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data.unzip_file manual__2024-04-15T12:13:48.859474+00:00 [queued]>
[2024-04-15T12:30:14.185+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data.unzip_file manual__2024-04-15T12:13:48.859474+00:00 [queued]>
[2024-04-15T12:30:14.186+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-04-15T12:30:14.200+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): unzip_file> on 2024-04-15 12:13:48.859474+00:00
[2024-04-15T12:30:14.208+0000] {standard_task_runner.py:60} INFO - Started process 1287 to run task
[2024-04-15T12:30:14.212+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_data', 'unzip_file', 'manual__2024-04-15T12:13:48.859474+00:00', '--job-id', '1776', '--raw', '--subdir', 'DAGS_FOLDER/etl_data.py', '--cfg-path', '/tmp/tmp61l9xa8c']
[2024-04-15T12:30:14.214+0000] {standard_task_runner.py:88} INFO - Job 1776: Subtask unzip_file
[2024-04-15T12:30:14.254+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_data.unzip_file manual__2024-04-15T12:13:48.859474+00:00 [running]> on host fdd3cfdf3f53
[2024-04-15T12:30:14.321+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data' AIRFLOW_CTX_TASK_ID='unzip_file' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T12:13:48.859474+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-15T12:13:48.859474+00:00'
[2024-04-15T12:30:14.323+0000] {logging_mixin.py:188} INFO - Error: File ./tolldata.tgz not found.
[2024-04-15T12:30:14.324+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-15T12:30:14.521+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_data, task_id=unzip_file, execution_date=20240415T121348, start_date=20240415T123014, end_date=20240415T123014
[2024-04-15T12:30:14.544+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-15T12:30:14.567+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
